<section class="id24-prefooter">
    <div class="container">
        <div class="prefooter-left">
            <h3 class="headline highlight">Sicher und übersichtlich</h3>
            <p>Egal, ob von zu Hause oder unterwegs. Sie haben jederzeit volle Kontrolle über alle Versicherungen und Dokumente.</p>
            <a class="btn btn-primary btn-block"
               href="<?= $this->escapeHtml($novumConfig['uri']) ?>insuredirect/de/register"
               title="Jetzt kostenlos registrieren">Jetzt kostenlos registrieren</a>
        </div>
    </div>
</section>