# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

updates:
  - package-ecosystem: "composer"

    directory: "/"

    schedule:
      interval: "daily"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "master"

    commit-message:
      include: "scope"
      prefix: "composer"

    ignore:
      - dependency-name: "browscap/browscap"
      - dependency-name: "elasticsearch/elasticsearch"
      - dependency-name: "endorphin-studio/browser-detector-tests"
      - dependency-name: "illuminate/config"
      - dependency-name: "illuminate/container"
      - dependency-name: "illuminate/contracts"
      - dependency-name: "illuminate/events"
      - dependency-name: "illuminate/filesystem"
      - dependency-name: "illuminate/view"
      - dependency-name: "infection/infection"
      - dependency-name: "laminas/laminas-diactoros"
      - dependency-name: "laminas/laminas-servicemanager"
      - dependency-name: "nikic/php-parser"
      - dependency-name: "phpunit/phpunit"
      - dependency-name: "predis/predis"
      - dependency-name: "psr/container"
      - dependency-name: "psr/http-message"
      - dependency-name: "psr/log"
      - dependency-name: "psr/simple-cache"
      - dependency-name: "symfony/console"
      - dependency-name: "symfony/filesystem"
      - dependency-name: "symfony/finder"
      - dependency-name: "symfony/http-foundation"
      - dependency-name: "symfony/yaml"

    rebase-strategy: "auto"

  - package-ecosystem: "npm"

    directory: "/"

    schedule:
      interval: "daily"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "master"

    commit-message:
      include: "scope"
      prefix: "npm"

    ignore:
      - dependency-name: "@csstools/postcss-cascade-layers"
      - dependency-name: "@csstools/postcss-color-function"
      - dependency-name: "@csstools/postcss-font-format-keywords"
      - dependency-name: "@csstools/postcss-is-pseudo-class"
      - dependency-name: "@csstools/postcss-nested-calc"
      - dependency-name: "@csstools/postcss-normalize-display-values"
      - dependency-name: "@csstools/postcss-text-decoration-shorthand"
      - dependency-name: "@csstools/postcss-trigonometric-functions"
      - dependency-name: "@csstools/postcss-unset-value"
      - dependency-name: "@localnerve/imagemin-gifsicle"
      - dependency-name: "@localnerve/imagemin-pngquant"
      - dependency-name: "@node-minify/core"
      - dependency-name: "@node-minify/no-compress"
      - dependency-name: "@node-minify/terser"
      - dependency-name: "@types/node"
      - dependency-name: "@typescript-eslint/eslint-plugin"
      - dependency-name: "@typescript-eslint/parser"
      - dependency-name: "@typescript-eslint/typescript-estree"
      - dependency-name: "@vheemstra/vite-plugin-imagemin"
      - dependency-name: "@vitest/coverage-istanbul"
      - dependency-name: "@vitest/ui"
      - dependency-name: "cssnano"
      - dependency-name: "cssnano-preset-default"
      - dependency-name: "esbuild"
      - dependency-name: "imagemin"
      - dependency-name: "postcss-color-hex-alpha"
      - dependency-name: "postcss-color-rebeccapurple"
      - dependency-name: "postcss-custom-media"
      - dependency-name: "postcss-custom-properties"
      - dependency-name: "postcss-custom-selectors"
      - dependency-name: "postcss-dir-pseudo-class"
      - dependency-name: "postcss-focus-visible"
      - dependency-name: "postcss-focus-within"
      - dependency-name: "postcss-gap-properties"
      - dependency-name: "postcss-image-set-function"
      - dependency-name: "postcss-load-config"
      - dependency-name: "postcss-nesting"
      - dependency-name: "postcss-overflow-shorthand"
      - dependency-name: "postcss-preset-env"
      - dependency-name: "postcss-pseudo-class-any-link"
      - dependency-name: "postcss-selector-not"
      - dependency-name: "supports-color"
      - dependency-name: "vitest"

    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "daily"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "master"

    commit-message:
      prefix: "github-actions"

    ignore:
      - dependency-name: "mimmi20/ci"

    rebase-strategy: "auto"
