<?php
/* @var $form \Laminas\Form\Form */

$form->prepare();
?>

<h1 class="card-header">Alttarifbewertung</h1>
<div class="card-body" id="atb-start">
    <div class="text-container">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title">Alttarifbewertung</div>
            <div class="alert alert-danger" role="alert">
                Es ist ein Fehler aufgetreten!
            </div>
            <div class="alert alert-warning" role="alert">
                Ihre angegebenen Daten sind nicht korrekt!
            </div>

            <?= $this->form()->openTag($form); ?>
                <fieldset class="col-12">
                    <legend class="form-label">Vertragsart</legend>
                    <select class="form-select is-invalid" name="productType" id="productType" data-next="company" required data-required-message="Bitte wählen Sie eine Vertragsart." aria-label="Vertragsart" autocomplete="off">
                        <option value="">Vertragsart wählen</option>
                        <option value="12 ">Hausrat</option>
                        <option value="123 ">Privathaftpflicht</option>
                        <option value="1234 ">Rechtsschutz</option>
                        <option value="12345 ">Tierhalterhaftpflicht für Hunde</option>
                        <option value="123456 ">Tierhalterhaftpflicht für Pferde</option>
                        <option value="1234567 ">Unfall</option>
                        <option value="12345678 ">Wohngebäude</option>
                    </select>
                    <div class="invalid-feedback">Bitte wählen Sie eine Vertragsart.</div>
                </fieldset>

                <div class="col-12 position-relative">
                    <button class="btn info-layer-trigger position-absolute top-0 end-0 icon" data-layer="info-layer-company"><i class="bi bi-info-circle"></i></button>
                    <fieldset class="col-12" data-name="company" disabled>
                        <legend class="form-label position-relative pe-4">Versicherer</legend>
                        <select class="form-select is-invalid" name="company" id="company" data-next="year" required aria-label="Versicherer" autocomplete="off">
                            <option value="">Versicherer wählen</option>
                            <option value="1234 ">Allianz</option>
                            <option value="12345 ">nicht Allianz</option>
                        </select>
                        <div class="invalid-feedback">Bitte wählen Sie einen Versicherer.</div>
                    </fieldset>
                </div>

                <div class="col-12 position-relative">
                    <button class="btn info-layer-trigger position-absolute top-0 end-0 icon" data-layer="info-layer-year"><i class="bi bi-info-circle"></i></button>
                    <fieldset class="col-12 position-relative" data-name="year" disabled>
                        <legend class="form-label position-relative pe-4">Tarifstand</legend>
                        <select class="form-select" name="year" id="year" data-next="product" required aria-label="Tarifstand" autocomplete="off">
                            <option value="">Tarifstand wählen</option>
                            <option value="1234 ">heute</option>
                            <option value="12345 ">gestern</option>
                        </select>
                        <div class="invalid-feedback">Bitte wählen Sie einen Tarifstand.</div>
                        <div class="form-text">
                            <strong>Tipp:</strong> <?= $this->escapeHtml($this->translate('type the tariff generation to improve results')) ?>
                        </div>
                    </fieldset>
                </div>

                <fieldset class="col-12" data-name="product" disabled>
                    <legend class="form-label">Tarifname</legend>
                    <select class="form-select" name="product" id="product" data-next="prod-opt" required aria-label="Tarifname" autocomplete="off">
                        <option value="">Tarifname wählen</option>
                        <option value="1234 ">Tarif 1</option>
                        <option value="12345 ">Tarif 2</option>
                    </select>
                    <div class="invalid-feedback">Bitte wählen Sie einen Tarifnamen.</div>
                </fieldset>

                <fieldset class="col-12" data-name="prod-opt" disabled>
                    <legend class="form-label">Tarifausprägungen</legend>
                    <select class="form-select" name="prod-opt" id="prod-opt" aria-label="Tarifausprägungen" autocomplete="off">
                        <option value="">Tarifausprägungen wählen</option>
                        <option value="1234 ">alles enthalten</option>
                        <option value="12345 ">nichts enthalten</option>
                    </select>
                    <div class="invalid-feedback">Bitte wählen Sie eine Tarifausprägung aus.</div>
                </fieldset>

                <!-- RS -->
                <fieldset class="col-12 d-none has-spinner" data-name="contract-type" disabled>
                    <legend class="form-label align-items-center">Vertragsart <span class="form-text">(Mehrfachauswahl möglich)</span></legend>
                </fieldset>

                <!-- WG -->
                <fieldset class="col-12 d-none has-spinner" data-name="danger-type" disabled>
                    <legend class="form-label align-items-center">Gefahren <span class="form-text">(Mehrfachauswahl möglich)</span></legend>
                    <div class="invalid-feedback">Bitte wählen Sie die versicherten Gefahren aus.</div>
                </fieldset>

                <!-- Unfall -->
                <fieldset class="col-12 d-none" data-name="tax-type" disabled>
                    <legend class="form-label">Gliedertaxen</legend>
                    <select class="form-select" name="tax-type" id="tax-type" required aria-label="Gliedertaxen" autocomplete="off">
                        <option value="">Gliedertaxe wählen</option>
                    </select>
                    <div class="invalid-feedback">Bitte wählen Sie die Gliedertaxe aus.</div>
                </fieldset>

                <div class="col-12 button-group text-center">
                    <button type="submit" class="btn btn-primary loading-btn js-gtm-event">
                        weiter
                    </button>
                </div>
                <div class="form-text"><sup class="text-danger">*</sup> Pflichtfeld</div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
    <div class="text-container">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
</div>
<div class="card-body" id="atb-result">
    <div class="card mb-3">
        <div class="card-header">
            <div class="headline">Leistung</div>
            <hr/>
            <div class="text text-center">bis zu <strong>xx%</strong> mehr Leistung</div>
        </div>
        <div class="card-body">
            <div class="pie-chart">
                <div class="align-self-center current-rate">
                    <svg viewBox="0 0 36 36" class="circular-chart">
                        <path class="circle-bg bg" stroke-dasharray="101 101" d="M18 2 a 16 16 0 0 1 0 32 a 16 16 0 0 1 0 -32" />
                        <path class="circle-bg secondary circle" stroke-dasharray="19 100" d="M18 2 a 16 16 0 0 1 0 32 a 16 16 0 0 1 0 -32" />
                        <text x="50%" y="50%" class="text secondary">41%</text>
                    </svg>
                    <div class="description text-center"><?= $this->escapeHtml($this->translate('your tariff')) ?></div>
                </div>

                <div class="align-self-center best-rate">
                    <svg viewBox="0 0 36 36" class="circular-chart">
                        <path class="circle-bg bg" stroke-dasharray="101 101" d="M18 2 a 16 16 0 0 1 0 32 a 16 16 0 0 1 0 -32" />
                        <path class="circle-bg primary" stroke-dasharray="20 100" d="M18 2 a 16 16 0 0 1 0 32 a 16 16 0 0 1 0 -32" />
                        <text x="50%" y="50%" class="text primary">42%</text>
                    </svg>
                    <div class="description text-center"><?= $this->escapeHtml($this->translate('best tariff')) ?></div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <div class="headline">Leistungskriterien</div>
        </div>
        <div class="card-body">
            <div class="accordion border-bottom-0" id="accordeon-0">
                <details class="accordion-item border-bottom-0">
                    <summary class="accordion-button">
                        <div class="accordion-header user-select-none col-12">
                            <div class="row g-0">
                                <div class="col-12 col-md-5 position-relative g-2">
                                    Text 1
                                </div>
                                <div class="col-12 col-md-7 position-relative g-2">
                                    <div class="row gy-2 gx-0">
                                        <div class="col-11 progress-chart-current-rate secondary">
                                            <progress class="progress" max="100" value="82"></progress>
                                        </div>
                                        <div class="col-1 progress-chart-text text-end">82 %</div>
                                        <div class="col-11 progress-chart-current-rate primary">
                                            <progress class="progress" max="100" value="92"></progress>
                                        </div>
                                        <div class="col-1 progress-chart-text text-end">92 %</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </summary>
                    <div class="accordion-body">
                        <div class="row g-0">
                            <div class="col-12 col-md-5 position-relative accordion-default-header text-truncate">
                                text <button class="btn info-layer-trigger position-absolute top-0 end-0 icon" data-layer="info-layer-topic1"><i class="bi bi-info-circle"></i></button>
                            </div>
                            <div class="col-12 col-md-7 g-2">
                                <div class="row gx-0 gy-2">
                                    <div class="col-11 progress-chart-best-rate secondary">
                                        <progress class="progress" max="100" value="42"></progress>
                                    </div>
                                    <div class="col-1 progress-chart-text text-end">42 %</div>

                                    <div class="col-11 progress-chart-current-rate primary">
                                        <progress class="progress" max="100" value="52"></progress>
                                    </div>
                                    <div class="col-1 progress-chart-text text-end">52 %</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </details>
                <details class="accordion-item">
                    <summary class="accordion-button">
                        <div class="accordion-header user-select-none col-12">
                            <div class="row g-0">
                                <div class="col-12 col-md-5 position-relative g-2">
                                    Text 2
                                </div>
                                <div class="col-12 col-md-7 position-relative g-2">
                                    <div class="row gy-2 gx-0">
                                        <div class="col-11 progress-chart-current-rate secondary">
                                            <progress class="progress" max="100" value="12"></progress>
                                        </div>
                                        <div class="col-1 progress-chart-text text-end">12 %</div>
                                        <div class="col-11 progress-chart-current-rate primary">
                                            <progress class="progress" max="100" value="22"></progress>
                                        </div>
                                        <div class="col-1 progress-chart-text text-end">22 %</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </summary>
                    <div class="accordion-body">
                        <div class="row g-0">
                            <div class="col-12 col-md-5 position-relative accordion-default-header text-truncate">
                                text 2 <button class="btn info-layer-trigger position-absolute top-0 end-0 icon" data-layer="info-layer-topic2"><i class="bi bi-info-circle"></i></button>
                            </div>
                            <div class="col-12 col-md-7 g-2">
                                <div class="row gx-0 gy-2">
                                    <div class="col-11 progress-chart-best-rate secondary">
                                        <progress class="progress" max="100" value="24"></progress>
                                    </div>
                                    <div class="col-1 progress-chart-text text-end">24 %</div>

                                    <div class="col-11 progress-chart-current-rate primary">
                                        <progress class="progress" max="100" value="64"></progress>
                                    </div>
                                    <div class="col-1 progress-chart-text text-end">64 %</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </details>
            </div>
        </div>
        <div class="card-footer text-center">
            <a class="default-link text-decoration-none" href="javascript:history.back()"> &laquo; Angaben ändern</a>
        </div>
    </div>
</div>

<?php //layer ?>
<dialog class="modal" id="info-layer-company" aria-hidden="true" aria-labelledby="modal-title-insurer" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <header class="modal-header">
                <h5 class="modal-title" id="modal-title-insurer">Versicherer</h5>
                <button type="button" class="btn-close close" aria-label="Close" data-bs-dismiss="modal"></button>
            </header>
            <section class="modal-body">
                <p>
                    <?= $this->escapeHtml($this->translate('choose your current insurer')) ?>
                </p>
                <p>
                    <?= $this->escapeHtml($this->translate('if the insurer is not in our list')) ?>
                </p>
            </section>
            <footer class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </footer>
        </div>
    </div>
</dialog>
<dialog class="modal" id="info-layer-year" aria-hidden="true" aria-labelledby="modal-title-tariff" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <header class="modal-header">
                <h5 class="modal-title" id="modal-title-tariff">Tarifgeneration</h5>
                <button type="button" class="btn-close close" aria-label="Close" data-bs-dismiss="modal"></button>
            </header>
            <section class="modal-body">
                <p>
                    <?= $this->escapeHtml($this->translate('choose the generation of your current tariff')) ?>
                </p>
            </section>
        </div>
    </div>
</dialog>

<?php //layer ?>
<dialog class="modal" id="info-layer-topic1" aria-hidden="true" aria-labelledby="modal-title-topic1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <header class="modal-header">
                <h5 class="modal-title" id="modal-title-topic1">Topic 1</h5>
                <button type="button" class="btn-close close" aria-label="Close" data-bs-dismiss="modal"></button>
            </header>
            <section class="modal-body">
                <p>
                    Topic 1
                </p>
            </section>
            <footer class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </footer>
        </div>
    </div>
</dialog>
<dialog class="modal" id="info-layer-topic2" aria-hidden="true" aria-labelledby="modal-title-topic2" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <header class="modal-header">
                <h5 class="modal-title" id="modal-title-topic2">Topic 2</h5>
                <button type="button" class="btn-close close" aria-label="Close" data-bs-dismiss="modal"></button>
            </header>
            <section class="modal-body">
                <p>
                    Topic 2
                </p>
            </section>
        </div>
    </div>
</dialog>

<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('node_modules/bootswatch/dist/morph/bootstrap.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('public/css/atb.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/form.ts')); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/atb.ts'), 'module', ['id' => 'functional-script']); ?>
