<section class="content-wrapper faq-container container">
    <div class="row">
        <div class="col-12 col-md-8">
            <h1 class="headline highlight">Häufig gestellte Fragen</h1>
            <div class="accordion" id="faq">
                <details class="accordion-item" open>
                    <summary class="accordion-button" id="headingOne">
                        Lorem ipsum dolor sit amet?
                    </summary>

                    <div class="accordion-collapse accordion-body">
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                            invidunt ut labore et dolore magna aliquyam</p>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                            invidunt ut labore et dolore magna aliquyam</p>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                            invidunt ut labore et dolore magna aliquyam</p>
                    </div>
                </details>

                <details class="accordion-item">
                    <summary class="accordion-button" id="headingTwo">
                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
                        ut labore et
                    </summary>

                    <div class="accordion-collapse accordion-body">
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr</p>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                            invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
                            et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est
                            Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                            diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                            voluptua</p>
                    </div>
                </details>

                <details class="accordion-item">
                    <summary class="accordion-button" id="headingThree">
                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et
                    </summary>

                    <div class="accordion-collapse accordion-body">
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et</p>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy</p>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed</p>
                    </div>
                </details>
            </div>
        </div>
    </div>
</section>
