<h1 class="card-header">Häufig gestellte Fragen</h1>
<div class="card-body">
    <div class="accordion border-bottom-0" id="faq">
        <details class="accordion-item border-bottom-0" open>
            <summary class="accordion-button" id="headingOne">
                <div class="accordion-header user-select-none">Lorem ipsum dolor sit amet?</div>
            </summary>

            <div class="accordion-body border-bottom">
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                    invidunt ut labore et dolore magna aliquyam</p>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                    invidunt ut labore et dolore magna aliquyam</p>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                    invidunt ut labore et dolore magna aliquyam</p>
            </div>
        </details>

        <details class="accordion-item border-bottom-0">
            <summary class="accordion-button" id="headingTwo">
                <div class="accordion-header user-select-none">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
                ut labore et
                </div>
            </summary>

            <div class="accordion-body border-bottom">
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr</p>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                    invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
                    et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est
                    Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                    diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                    voluptua</p>
            </div>
        </details>

        <details class="accordion-item">
            <summary class="accordion-button" id="headingThree">
                <div class="accordion-header user-select-none">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et
                </div>
            </summary>

            <div class="accordion-body">
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et</p>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy</p>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed</p>
            </div>
        </details>
    </div>
</div>

<?php $this->inlineScript()->appendFile($this->viteUrl()->css('node_modules/bootstrap/dist/css/bootstrap.css')); ?>
