<?php
/* @var $form \Laminas\Form\Form */

$form->prepare();
?>

<h1 class="card-header">Hausrat</h1>
<div class="card-body" id="hr-start">
    <div class="text-container">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
    <?= $this->form()->openTag($form); ?>
    <fieldset class="card mb-2">
        <legend class="card-header"><span>Was möchten Sie versichern?</span></legend>

        <div class="card-body">
            <!-- form fields -->
            <?= $this->formRow($form->get('versbeginn')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('versbeginn_datum')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('plz')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('ort')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('strasse')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('hnr')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('link')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('gebdatum')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('whg')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vermietet')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('wohnfl')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('wohnfl_kg')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('kellerfl')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('beamte')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('verssummeauto')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('verssumme')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('fahrrad')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('glas')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('elem')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('grob')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('bauart')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('bauart-link')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2">
        <legend class="card-header"><span>Rabattrelevante Angaben</span></legend>

        <div class="card-body">
            <?= $this->formRow($form->get('selbst')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('laufzeit')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vorvers5')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('schaeden5')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('kombirabatte')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2" data-optional="1" data-show="ja">
        <legend class="card-header"><span>Kombirabatte für folgende Sparten-Kombinationen berücksichtigen</span></legend>

        <div class="card-body">
            <p class="text-center pt-2 text-info-discount">Kombirabatte - Je mehr Verträge bei einer Gesellschaft, um so günstigere Preise.
                Welche Verträge haben Sie schon oder haben vor, sie zu versichern?</p>


            <?= $this->formRow($form->get('KrPHV')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrTIE')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHUG')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrOEL')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrWG')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrWGGLS')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHR')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHRGLS')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrUNF')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrRS')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2">
        <div class="card-body">
            <?= $this->formRow($form->get('zusatzfragen')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2" data-detail="1" data-show="ja">
        <legend class="card-header"><span>Optionale Detailfragen</span></legend>
        <div class="card-body">
            <?= $this->formRow($form->get('links-standard')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('uver_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('ues_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('werts_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('dieb_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('dkfz_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('dkle_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('rauch_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('kfz_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('bank_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('dgar_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('was_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('seng_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('waver_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('hot_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('reis_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('arb_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('evors_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('all_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('sich_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('meld_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('bewo_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('tres_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('feu_v')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <div class="card mb-2">
        <div class="card-body">
            <?= $this->formRow($form->get('chkErstinfo')->setOption('form', $form)); ?>

            <a class="mt-0 w-100 text-left first-info" title="Erstinformation" href="https://www.geld.de/module/geld/data/erstinformation-jdc.pdf" download="https://www.geld.de/module/geld/data/erstinformation-jdc.pdf" target="_blank">Erstinformation herunterladen</a>

            <div class="mt-2 mb-3 w-100 bordered-box">
                <a class="text-decoration-none text-left pb-1 my-2 collapsed headline-bordered-box" data-toggle="collapse" href="#collapseFirstInfo" role="button" aria-expanded="false" aria-controls="collapseFirstInfo">
                    Mitteilung zur Beratungsgrundlage, § 60 VVG
                </a>
                <div class="collapse mt-2" id="collapseFirstInfo">
                    <p>
                        Im durchgeführten Produktvergleich wurden Hausratversicherungsverträge (nachfolgend das Versicherungsprodukt genannt) von 26 Versicherern und 7 Assekuradeuren (zusammen nachfolgend Gesellschaften genannt) berücksichtigt. Generell berücksichtigt der Vermittler keine so genannten Direktversicherer und Gesellschaften, welche dem Vermittler keine Courtage zahlen oder mit diesem nicht zusammenarbeiten.                    </p>
                    <p>
                        Nach der Recherche des Vergleichsprogrammherstellers, die anhand der von der Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin) veröffentlichten Versichererlisten<sup>1</sup> und anderer öffentlich zugänglicher Quellen durchgeführt wurde, bieten das Versicherungsprodukt 91 Versicherer auf dem deutschen Versicherungsmarkt an. Aufgrund des Umstandes, dass die BaFin keine gesonderte Versichererliste für das Versicherungsprodukt veröffentlich hat, und der eingeschränkten Recherchemöglichkeiten sind allerdings bzgl. der genannten Zahl der Versicherer Abweichungen möglich. Ferner sind auf dem deutschen Versicherungsmarkt Assekuradeure tätig, die für die Versicherer hinsichtlich des Versicherungsprodukts spezielle Deckungskonzepte entwickeln und diese unter dem Namen des Assekuradeurs am Markt anbieten. Eine Angabe der Zahl der Assekuradeure ist dem Vermittler nicht möglich, da die BaFin diesbzgl. keine Listen veröffentlicht.                    </p>
                    <p>
                        Die Empfehlung des Vermittlers beruht demnach auf einer eingeschränkten Versicherer- und Vertragsauswahl und damit auf einer eingeschränkten Beratungsgrundlage des Vermittlers.                    </p>
                    <p>
                        Dem Vermittler ist nicht bekannt, welchen Marktanteil die berücksichtigten Gesellschaften und Versicherungsverträge im Verhältnis zum gesamten deutschen Versicherungsmarkt halten. Der Vermittler hat keinen Zugang zu etwaigen Statistiken, aus denen er auch nur schätzungsweise Informationen zum Marktanteil der berücksichtigten Gesellschaften und Versicherungsverträge ableiten könnte. Es ist somit möglich, dass die von dem Vermittler berücksichtigten Gesellschaften und Versicherungsverträge nur einen geringen Marktanteil der in Deutschland angebotenen Versicherungen abdecken.                    </p>
                    <p>
                        Der Produktvergleich beruht nicht auf einer eigenen Marktuntersuchung des Vermittlers, sondern auf den Informationen einer marktüblichen Vergleichssoftware für Versicherungsvermittler.                    </p>
                    <p>
                        Gesellschaften, welche bei dem Produktvergleich berücksichtigt wurden, werden nachfolgend unter "Teilnehmende Gesellschaften" aufgelistet.                    </p>
                    <p>
                        <sup>1</sup> Quelle: https://portal.mvp.bafin.de/database/InstInfo/sucheForm.do                    </p>
                    <!-- Button trigger modal -->
                    <a class="text-center d-block insurer-list-link col-12 js-gtm-event" data-toggle="modal" data-target="#insurerList" data-event-type="click" data-event-category="versicherung" data-event-label="hr" data-event-action="participating companies">
                        Teilnehmende Gesellschaften
                    </a>

                    <!-- Modal -->
                    <div class="modal fade insurer-list" id="insurerList" tabindex="-1" role="dialog" aria-labelledby="insurerListModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content rounded-0">
                                <div class="modal-header rounded-0">
                                    <h5 class="modal-title" id="insurerListModalCenterTitle">Teilnehmende Gesellschaften</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">×</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <h6>Versicherer/ Versicherungsgesellschaften</h6>
                                    <ul>
                                        <li>AXA Versicherung AG (DBV)</li>
                                        <li>Alte Leipziger Versicherung Aktiengesellschaft</li>
                                        <li>BA die Bayerische Allgemeine Versicherung AG</li>
                                        <li>Badischer Gemeinde-Versicherungs-Verband</li>
                                        <li>Baloise Sachversicherung AG Deutschland</li>
                                        <li>BavariaDirekt Versicherung AG</li>
                                        <li>Concordia VVaG</li>
                                        <li>Die Haftpflichtkasse VVaG</li>
                                        <li>Docura VVaG</li>
                                        <li>GVO Gegenseitigkeit Versicherung Oldenburg VVaG</li>
                                        <li>Gothaer Allgemeine Versicherung AG</li>
                                        <li>INTER Allgemeine Versicherung AG</li>
                                        <li>Ideal Versicherung AG</li>
                                        <li>Janitos Versicherung AG</li>
                                        <li>Medien-Versicherung a.G. Karlsruhe</li>
                                        <li>NV-Versicherungen VVaG</li>
                                        <li>Neodigital AG</li>
                                        <li>Ostangler Brandgilde VVaG</li>
                                        <li>Rhion Versicherung AG</li>
                                        <li>VHV Allgemeine Versicherung AG</li>
                                        <li>Waldenburger Versicherung AG</li>
                                        <li>Zurich Versicherung Aktiengesellschaft</li>
                                        <li>Ammerländer Versicherung VVaG</li>
                                        <li>Grundeigentümer-Versicherung VVaG</li>
                                        <li>HanseMerkur Allge­meine Versi­che­rung AG</li>
                                        <li>Oberösterreichische Versicherung AG</li>
                                    </ul>
                                    <h6>Assekuradeure (Versicherungsdienstleister)</h6>
                                    <ul>
                                        <li>Adam Riese GmbH</li>
                                        <li>Adcuri GmbH</li>
                                        <li>ConceptIF Group AG</li>
                                        <li>Degenia Versicherungsdienst AG</li>
                                        <li>Domcura AG</li>
                                        <li>Konzept &amp; Marketing GmbH</li>
                                        <li>S.L.P. Vertriebsservice AG</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col-sm-8">
                    <div class="consulting-waiver-text">Bei Rückfragen stehen wir Ihnen gerne telefonisch zur Verfügung.</div>
                    <div>
                        <span class="consulting-waiver-hotline">
                            <a href="tel:+49xx" title="Hotline" class=" telephone">xx</a>
                        </span>
                        <span class="consulting-waiver-business-hours">
                            <span class="description">Mo - Fr:  xx - xx Uhr</span>
                        </span>
                    </div>
                    <div class="col-1 pl-0 pr-0 align-self-center">
                        <label class="m-0 icon icon-question consulting-waiver-info js-gtm-event" for="sxr-layer-consulting-waiver-1" data-event-type="click" data-event-category="versicherung" data-event-label="hr" data-event-action="consulting requested"></label>
                    </div>
                </div>

                <div class="col-sm-4 pt-2">
                    <?= $this->formRow($form->get('btn_berechnen')->setOption('form', $form)); ?>
                </div>
            </div>
        </div>
    </div>

    <?= $this->form()->closeTag(); ?>
    <div class="text-container">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
</div>

<div class="consulting-waiver-wrapper d-none">

    <div class="col-sm-8 align-self-end consulting-waiver">
        <div class="consulting-waiver-inner icon icon-phone">
            <div class="row ml-4">
                <div class="col-11">

                </div>
            </div>
        </div>

        <input type="checkbox" id="sxr-layer-consulting-waiver-1" class="d-none">
        <div class="layer-consulting-waiver">
            <div class="layer-consulting-waiver-container-row">
                <div class="layer-consulting-waiver-container-col">
                    <div class="layer-consulting-waiver-inner-col">
                        <label class="layer-consulting-waiver-close" for="sxr-layer-consulting-waiver-1">x</label>
                        <div class="layer-consulting-waiver-col">
                            <div class="layer-consulting-waiver-headline">Sie möchten eine Beratung?</div>
                            <div class="d-none d-sm-block icon icon-phone layer-consulting-waiver-icon"></div>
                            <div>
    <span class="consulting-waiver-hotline"><a href="tel:+49xx" title="Hotline" class=" telephone">xx</a>
</span>
                                <span class="consulting-waiver-business-hours">
<span class="description">Mo - Fr:  xx - xx Uhr</span>
</span></div>


                        </div>
                        <div class="mt-4 layer-consulting-waiver-col">
                            <div class="layer-consulting-waiver-headline">Schneller zum Vertrag?</div>
                            <div class="layer-consulting-waiver-description">
                                <p>So kommen Sie direkt zu Ihrer Versicherung</p>
                                <ol class="pl-3">
                                    <li>Klicken Sie auf "Berechnen".</li>
                                    <li>Machen Sie die nötigen Angaben.</li>
                                    <li>Bestätigen Sie vor dem Abschluss, dass Sie keine Beratung benötigen.</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('node_modules/bootswatch/dist/quartz/bootstrap.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('public/css/hr.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/form.ts')); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/hr.ts')); ?>
