<h1 class="card-header">Impressum</h1>
<div class="card-body">
    <p class="card-text">
        <strong>Lorem ipsum dolor sit</strong><br/>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr
    </p>
</div>

<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('node_modules/bootstrap/dist/css/bootstrap.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('public/css/navigation.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/dialog.ts')); ?>
