<?php
/* @var $form \Laminas\Form\Form */

$form->prepare();
?>

<div class="container">
    <div class="card mb-3">
        <div class="card-body">
            <h1 class="card-title">Lorem ipsum dolor sit amet, consetetur sadipscing</h1>
            <div class="card-text">
                <strong>Lorem ipsum dolor sit amet</strong>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat</p>
            </div>
        </div>
    </div>
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-6">
                <div class="card-body">
                    <h1 class="card-title">Lorem ipsum dolor</h1>
                    <div class="card-text row justify-content-start align-items-top">
                        <div class="col-12 col-sm-auto col-lg-12">
                            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed</p>
                            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 row my-0 mx-0 px-3 py-3">
                <?= $this->form($form) ?>
            </div>
        </div>
    </div>
</div>

