<?php
/* @var $form \Laminas\Form\Form */

$form->prepare();
?>

<?php $this->doctype(\Laminas\View\Helper\Doctype::HTML5); ?>

<h1 class="card-header">Haftpflicht</h1>
<div class="card-body" id="hr-start">
    <div class="text-wrapper">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
    <?= $this->form()->openTag($form); ?>
    <div class="alert alert-warning" role="alert">
        Ihre angegebenen Daten sind nicht korrekt!
    </div>

    <fieldset class="card mb-2">
        <legend class="card-header">Was möchten Sie versichern?</legend>

        <div class="card-body">
            <?= $this->formRow($form->get('single')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('versbeginn')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('versbeginn_datum')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('plz')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('beamte')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('gebdatum')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('ausfall')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('delikt')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('Hundn')->setOption('form', $form)); ?>
            <fieldset class="col-12 my-2 card" data-show="1">
                <legend class="card-header">Hund 1</legend>
                <div class="card-body has-margin">
                    <?= $this->formRow($form->get('Rasse_Tier1')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('mischling_hund1')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('Rasse_Tier1a')->setOption('form', $form)); ?>
                </div>
            </fieldset>
            <fieldset class="col-12 my-2 card" data-show="2">
                <legend class="card-header">Hund 2</legend>
                <div class="card-body has-margin">
                    <?= $this->formRow($form->get('Rasse_Tier2')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('mischling_hund2')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('Rasse_Tier2a')->setOption('form', $form)); ?>
                </div>
            </fieldset>
            <fieldset class="col-12 my-2 card" data-show="3">
                <legend class="card-header">Hund 3</legend>
                <div class="card-body has-margin">
                    <?= $this->formRow($form->get('Rasse_Tier3')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('mischling_hund3')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('Rasse_Tier3a')->setOption('form', $form)); ?>
                </div>
            </fieldset>
            <fieldset class="col-12 my-2 card" data-show="4">
                <legend class="card-header">Hund 4</legend>
                <div class="card-body has-margin">
                    <?= $this->formRow($form->get('Rasse_Tier4')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('mischling_hund4')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('Rasse_Tier4a')->setOption('form', $form)); ?>
                </div>
            </fieldset>
            <fieldset class="col-12 my-2 card" data-show="5">
                <legend class="card-header">Hund 5</legend>
                <div class="card-body has-margin">
                    <?= $this->formRow($form->get('Rasse_Tier5')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('mischling_hund5')->setOption('form', $form)); ?>
                    <?= $this->formRow($form->get('Rasse_Tier5a')->setOption('form', $form)); ?>
                </div>
            </fieldset>
        </div>
    </fieldset>

    <fieldset class="card mb-2">
        <legend class="card-header">Rabattrelevante Angaben</legend>

        <div class="card-body">
            <?= $this->formRow($form->get('laufzeit')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vorvers5')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('schaeden5')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('kombirabatte')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2" data-optional="1" data-show="ja">
        <legend class="card-header">Kombirabatte für folgende Sparten-Kombinationen berücksichtigen</legend>

        <div class="card-body">
            <p class="text-center pt-2 text-info-discount">Kombirabatte - Je mehr Verträge bei einer Gesellschaft, um so günstigere Preise.
                Welche Verträge haben Sie schon oder haben vor, sie zu versichern?</p>

            <?= $this->formRow($form->get('KrPHV')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrTIE')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHUG')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrOEL')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrWG')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrWGGLS')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHR')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHRGLS')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrUNF')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrRS')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2">
        <div class="card-body">
            <?= $this->formRow($form->get('zusatzfragen')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2" data-detail="1" data-show="ja">
        <legend class="card-header">Optionale Detailfragen</legend>
        <div class="card-body">
            <?= $this->formRow($form->get('links-standard')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vs_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vsm_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vsv_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('best_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('sgwe_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('ew_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('unbgru_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('einlw_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('fewoi_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('fewoa_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('fach_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('tier_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('oel_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('oelwo_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('allm_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('gewsa_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('abwa_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('inet_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('gef_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('geli_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('sv_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('sva_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('svd_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('welt_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('elt_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('ehr_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('tagmu_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('regr_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('bau_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('surf_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('tiere_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('wafa_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('flug_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('drohne_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('jagd_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('foto_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('rsausfall')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <div class="card mb-2">
        <div class="card-body">
            <?= $this->formRow($form->get('chkErstinfo')->setOption('form', $form)); ?>

            <a class="mt-0 w-100 text-left first-info" title="Erstinformation" href="https://www.geld.de/module/geld/data/erstinformation-jdc.pdf" download="https://www.geld.de/module/geld/data/erstinformation-jdc.pdf" target="_blank">Erstinformation herunterladen</a>

            <div class="accordion mt-3">
                <details class="accordion-item border-bottom-0">
                    <summary class="accordion-button" id="headingTwo">
                        <div class="accordion-header user-select-none">
                            Mitteilung zur Beratungsgrundlage, § 60 VVG
                        </div>
                    </summary>
                    <div class="accordion-body border-bottom">
                        <p>
                            Im durchgeführten Produktvergleich wurden Hausratversicherungsverträge (nachfolgend das Versicherungsprodukt genannt) von 26 Versicherern und 7 Assekuradeuren (zusammen nachfolgend Gesellschaften genannt) berücksichtigt. Generell berücksichtigt der Vermittler keine so genannten Direktversicherer und Gesellschaften, welche dem Vermittler keine Courtage zahlen oder mit diesem nicht zusammenarbeiten.                    </p>
                        <p>
                            Nach der Recherche des Vergleichsprogrammherstellers, die anhand der von der Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin) veröffentlichten Versichererlisten<sup>1</sup> und anderer öffentlich zugänglicher Quellen durchgeführt wurde, bieten das Versicherungsprodukt 91 Versicherer auf dem deutschen Versicherungsmarkt an. Aufgrund des Umstandes, dass die BaFin keine gesonderte Versichererliste für das Versicherungsprodukt veröffentlich hat, und der eingeschränkten Recherchemöglichkeiten sind allerdings bzgl. der genannten Zahl der Versicherer Abweichungen möglich. Ferner sind auf dem deutschen Versicherungsmarkt Assekuradeure tätig, die für die Versicherer hinsichtlich des Versicherungsprodukts spezielle Deckungskonzepte entwickeln und diese unter dem Namen des Assekuradeurs am Markt anbieten. Eine Angabe der Zahl der Assekuradeure ist dem Vermittler nicht möglich, da die BaFin diesbzgl. keine Listen veröffentlicht.                    </p>
                        <p>
                            Die Empfehlung des Vermittlers beruht demnach auf einer eingeschränkten Versicherer- und Vertragsauswahl und damit auf einer eingeschränkten Beratungsgrundlage des Vermittlers.                    </p>
                        <p>
                            Dem Vermittler ist nicht bekannt, welchen Marktanteil die berücksichtigten Gesellschaften und Versicherungsverträge im Verhältnis zum gesamten deutschen Versicherungsmarkt halten. Der Vermittler hat keinen Zugang zu etwaigen Statistiken, aus denen er auch nur schätzungsweise Informationen zum Marktanteil der berücksichtigten Gesellschaften und Versicherungsverträge ableiten könnte. Es ist somit möglich, dass die von dem Vermittler berücksichtigten Gesellschaften und Versicherungsverträge nur einen geringen Marktanteil der in Deutschland angebotenen Versicherungen abdecken.                    </p>
                        <p>
                            Der Produktvergleich beruht nicht auf einer eigenen Marktuntersuchung des Vermittlers, sondern auf den Informationen einer marktüblichen Vergleichssoftware für Versicherungsvermittler.                    </p>
                        <p>
                            Gesellschaften, welche bei dem Produktvergleich berücksichtigt wurden, werden nachfolgend unter "Teilnehmende Gesellschaften" aufgelistet.                    </p>
                        <p>
                            <sup>1</sup> Quelle: https://portal.mvp.bafin.de/database/InstInfo/sucheForm.do
                        </p>
                        <!-- Button trigger modal -->
                        <a class="text-center d-block col-12 info-layer-trigger" data-layer="insurerList">
                            Teilnehmende Gesellschaften
                        </a>
                    </div>
                </details>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body no-margin">
            <div class="row align-items-center">
                <div class="col-sm-8">
                    <div class="row g-0 align-items-center">
                        <div class="col-1 align-middle fs-1"><i class="bi bi-telephone-fill"></i></div>
                        <div class="col-4">
                            <p>Bei Rückfragen stehen wir Ihnen gerne telefonisch zur Verfügung.</p>
                            <p><a href="tel:+49xx" title="Hotline" class="fs-5">xx</a></p>
                            <p><span class="fs-6">Mo - Fr:  xx - xx Uhr</span></p>
                        </div>
                        <button class="btn info-layer-trigger col-1 align-middle fs-1" data-layer="info-layer-consulting"><i class="bi bi-question-circle"></i></button>
                    </div>
                </div>

                <div class="col-sm-4 pt-2">
                    <?= $this->formRow($form->get('btn_berechnen')->setOption('form', $form)); ?>
                </div>
            </div>
        </div>
    </div>

    <?= $this->formHidden($form->get('zahlweise')->setOption('form', $form)); ?>
    <?= $this->formHidden($form->get('chkFilterNachhaltigkeit')->setOption('form', $form)); ?>

    <?= $this->form()->closeTag(); ?>
    <div class="text-wrapper">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
</div>

<dialog class="modal" id="insurerList" aria-labelledby="insurerListModalCenterTitle" aria-hidden="true" aria-modal="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="insurerListModalCenterTitle">Teilnehmende Gesellschaften</h5>
                <button type="button" class="btn-close close" aria-label="Close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <h6>Versicherer/ Versicherungsgesellschaften</h6>
                <ul>
                    <li>AXA Versicherung AG (DBV)</li>
                    <li>Alte Leipziger Versicherung Aktiengesellschaft</li>
                    <li>BA die Bayerische Allgemeine Versicherung AG</li>
                    <li>Badischer Gemeinde-Versicherungs-Verband</li>
                    <li>Baloise Sachversicherung AG Deutschland</li>
                    <li>BavariaDirekt Versicherung AG</li>
                    <li>Concordia VVaG</li>
                    <li>Die Haftpflichtkasse VVaG</li>
                    <li>Docura VVaG</li>
                    <li>GVO Gegenseitigkeit Versicherung Oldenburg VVaG</li>
                    <li>Gothaer Allgemeine Versicherung AG</li>
                    <li>INTER Allgemeine Versicherung AG</li>
                    <li>Ideal Versicherung AG</li>
                    <li>Janitos Versicherung AG</li>
                    <li>Medien-Versicherung a.G. Karlsruhe</li>
                    <li>NV-Versicherungen VVaG</li>
                    <li>Neodigital AG</li>
                    <li>Ostangler Brandgilde VVaG</li>
                    <li>Rhion Versicherung AG</li>
                    <li>VHV Allgemeine Versicherung AG</li>
                    <li>Waldenburger Versicherung AG</li>
                    <li>Zurich Versicherung Aktiengesellschaft</li>
                    <li>Ammerländer Versicherung VVaG</li>
                    <li>Grundeigentümer-Versicherung VVaG</li>
                    <li>HanseMerkur Allge­meine Versi­che­rung AG</li>
                    <li>Oberösterreichische Versicherung AG</li>
                </ul>
                <h6>Assekuradeure (Versicherungsdienstleister)</h6>
                <ul>
                    <li>Adam Riese GmbH</li>
                    <li>Adcuri GmbH</li>
                    <li>ConceptIF Group AG</li>
                    <li>Degenia Versicherungsdienst AG</li>
                    <li>Domcura AG</li>
                    <li>Konzept &amp; Marketing GmbH</li>
                    <li>S.L.P. Vertriebsservice AG</li>
                </ul>
            </div>
        </div>
    </div>
</dialog>

<?php $this->headLink()->prependStylesheet($this->viteUrl()->css('node_modules/bootstrap/dist/css/bootstrap.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('public/css/phv.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('public/css/help.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('public/css/navigation.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->css('public/css/accordion.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/form.ts')); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/phv.ts')); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/versbeginn.ts')); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->js('public/js/dialog.ts'), 'module'); ?>
