<?php
/* @var $form \Laminas\Form\Form */

$form->prepare();
?>

<?php $this->doctype(\Laminas\View\Helper\Doctype::HTML5); ?>

<h1 class="card-header">Haftpflicht</h1>
<div class="card-body" id="hr-start">
    <div class="text-container">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title">Haftpflicht berechnen</div>
            <div class="alert alert-danger" role="alert">
                Es ist ein Fehler aufgetreten!
            </div>
            <div class="alert alert-warning" role="alert">
                Ihre angegebenen Daten sind nicht korrekt!
            </div>

            <?= $this->form()->setIndent(16)->render($form) ?>
        </div>
    </div>
    <div class="text-container">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
</div>

<?php $this->headLink()->appendStylesheet('/css/phv.css', 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->inlineScript()->appendFile('/js/form.js'); ?>
<?php $this->inlineScript()->appendFile('/js/phv.js'); ?>
