<?php
/* @var $form \Laminas\Form\Form */

$form->prepare();
?>

<h1 class="card-header">Rechtsschutz</h1>
<div class="card-body" id="hr-start">
    <div class="text-wrapper">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
    <?= $this->form()->openTag($form); ?>
    <div class="alert alert-warning" role="alert">
        Ihre angegebenen Daten sind nicht korrekt!
    </div>

    <fieldset class="card mb-2">
        <legend class="card-header">Was möchten Sie versichern?</legend>

        <div class="card-body">
            <fieldset class="checkbox-group my-2 align-items-center">
                <legend class="col-form-label col-2" aria-label="Wählen Sie den Bereich, den Sie verscihern möchten"></legend>
                <div class="tile-wrapper">
                    <?= $this->formCheckbox($form->get('tarif_privat')->setOption('form', $form)) ?>
                </div>
                <div class="tile-wrapper">
                    <?= $this->formCheckbox($form->get('tarif_beruf')->setOption('form', $form)) ?>
                </div>
                <div class="tile-wrapper">
                    <?= $this->formCheckbox($form->get('tarif_verkehr_familie')->setOption('form', $form)) ?>
                </div>
                <div class="tile-wrapper">
                    <?= $this->formCheckbox($form->get('tarif_miete')->setOption('form', $form)) ?>
                </div>
                <div class="tile-wrapper">
                    <?= $this->formCheckbox($form->get('tarif_verkehr')->setOption('form', $form)) ?>
                </div>
            </fieldset>
            <div class="toast offset-sm-2 mb-3" data-show="p">
                <div class="toa"></div>
                <div class="toast-header"><strong>Privater Bereich</strong></div>
                <div class="toast-body">
                    <p>Dieser Baustein schützt Sie in privaten Rechtsstreitigkeiten, wie Vertrags- und Sach-, Internet- oder Steuerrecht.</p>
                    <p><strong>Beispiel: Rechtsschutz im Vertrags- und Sachenrecht</strong><br>Bei der Montage einer gelieferten Küche durch den Einbau-Service eines Möbelhauses wird diese beschädigt. Der Ersatz kann auf dem Klageweg durchgesetzt werden. Kosten: ca. 1.120 €</p>
                    <p><strong>Beispiel: Schadenersatz-Rechtsschutz</strong><br>Durchsetzen einer Schadenersatzforderung nach einem Unfall aufgrund eines fahrlässigen Skifahrers. Kosten: ca. 4.000 €</p>
                </div>
            </div>
            <div class="toast offset-sm-2 mb-3" data-show="b">
                <div class="toast-header"><strong>Arbeit &amp; Beruf</strong></div>
                <div class="toast-body">
                    <p>Dieser Baustein schützt Sie bei Auseinandersetzungen rund um das Arbeitsverhältnis, z.B. bei Kündigung durch den Arbeitgeber, oder wenn dieser Ihnen Geld schuldet. Ebenfalls besteht Schutz bei dienst- und versorgungsrechtlichen Ansprüchen in einem öffentlich-rechtlichen Dienstverhältnis, zum Beispiel Streitigkeiten hinsichtlich der Einstufung in eine bestimmte Besoldungsgruppe, Beförderungen, Versetzungen  oder Beihilfen im Krankheitsfall.</p>
                    <p><strong>Beispiel: Arbeits-Rechtsschutz:</strong><br>Nach einer überraschenden fristlosen Kündigung setzt der Versicherungsnehmer sich vor Gericht gegen seinen Arbeitgeber durch. Die Kündigung wird aufgehoben und die ausgefallenen Gehaltszahlungen in der Höhe von 30.000 Euro erstattet. Kosten: ca. 4000 €</p>
                </div>
            </div>
            <div class="toast offset-sm-2 mb-3" data-show="f">
                <div class="toast-header"><strong>Verkehr</strong></div>
                <div class="toast-body">
                    <p>Streitigkeiten im Straßenverkehr, z.B. Verkehrsunfall und Ordnungswidrigkeiten</p>
                    <p><strong>Beispiel: Ordnungswidrigkeiten-Rechtsschutz</strong><br>
                        Der Versicherungsnehmer droht nach einer Geschwindigkeitsüberschreitung von mehr als 30 Stundenkilometern in einer Autobahnbaustelle ein Fahrverbot, er ist beruflich jedoch sehr viel mit dem Auto unterwegs. Mithilfe eines Anwalts erwirkt er im Bußgeldverfahren vor Gericht ein höheres Bußgeld, darf seinen Führerschein jedoch behalten und gefährdet somit seinen Arbeitsplatz nicht. Kosten: ca. 3.400 €</p>
                    <p><strong>Beispiel: Schadenersatz-Rechtsschutz</strong><br>
                        Einklagen von Schmerzensgeld nach einem Verkehrsunfall, da der Unfallgegner dem Versicherungsnehmer die Vorfahrt genommen hat. Kosten: ca. 4.000€ </p>
                </div>
            </div>
            <div class="toast offset-sm-2 mb-3" data-show="m">
                <div class="toast-header"><strong>Eigentum &amp; Mieter</strong></div>
                <div class="toast-body">
                    <p>Wer gegen seinen Nachbarn vor Gericht ziehen möchte, muss mit teils erheblichen Kosten rechnen: Anwalt- und Gerichtsgebühren und möglicherweise Sachverständigenkosten.  Rechtsschutzversicherung mit diesem Baustein übernimmt diese Kosten.</p>
                    <p><strong>Beispiel: Immobilienrecht</strong><br>
                        Ein Nachbar fühlt sich vom Sohn des Versicherungsnehmers gestört, da dieser begonnen hat, Saxophon zu spielen. Er klagt daraufhin auf Unterlassung der Ruhestörung,. Ein Sachverständiger wird beauftragt, um den Lärmpegel zu messen.<br>
                        Kosten: ca. 3.500 €</p>
                    <p><strong>Beispiel: Mietrecht</strong><br>
                        Der Vermieter erhöht die Miete unverhältnismäßig. Mithilfe eines Sachverständigengutachtens setzt sich die Versicherungsnehmerin vor Gericht gegen den Vermieter durch. Kosten: ca. 2.500 €</p>
                </div>
            </div>
            <div class="toast offset-sm-2 mb-3" data-show="v">
                <div class="toast-header"><strong>Verkehr nur für den Versicherungsnehmer</strong></div>
                <div class="toast-body">
                    <p>Dieser Baustein ist nur einzeln versicherbar.</p>
                    <p><strong>Verkehr nur für den VN: </strong></p>
                    <p>
                        Versichert sind:
                        <ul>
                            <li>Die im Antrag genannten KFZ, müssen auf den VN zugelassen sein</li>
                            <li>Versicherungsnehmer (VN) als Fahrer der eigenen und auch fremder Fahrzeuge</li>
                            <li>Alle Fahrer der versicherten Fahrzeuge</li>
                        </ul>
                    </p>
                </div>
            </div>
            <?= $this->formRow($form->get('vermiet')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('OB1')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('OB2')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('OB3')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('OB4')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('OB5')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('OB6')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('cyber')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2">
        <legend class="card-header">Weitere Angaben</legend>

        <div class="card-body">
            <?= $this->formRow($form->get('plz')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('famstand')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('gebdatum')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('geburtsdatumPartner')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('anag')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('umsatzselbst')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2">
        <legend class="card-header">Rabattrelevante Angaben</legend>

        <div class="card-body">
            <?= $this->formRow($form->get('laufzeit')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vorvers5')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('wannschaden')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('kombirabatte')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2" data-optional="1" data-show="ja">
        <legend class="card-header">Kombirabatte für folgende Sparten-Kombinationen berücksichtigen</legend>

        <div class="card-body">
            <p class="text-center pt-2 text-info-discount">Kombirabatte - Je mehr Verträge bei einer Gesellschaft, um so günstigere Preise.
                Welche Verträge haben Sie schon oder haben vor, sie zu versichern?</p>

            <?= $this->formRow($form->get('KrPHV')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrTIE')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHUG')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrOEL')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrWG')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrWGGLS')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHR')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrHRGLS')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrUNF')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('KrRS')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2">
        <div class="card-body">
            <?= $this->formRow($form->get('zusatzfragen')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <fieldset class="card mb-2" data-detail="1" data-show="ja">
        <legend class="card-header">Optionale Detailfragen</legend>
        <div class="card-body">
            <?= $this->formRow($form->get('links-standard')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('vs_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('kaution_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('folge_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('ehestreit_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('unterhalt_v')->setOption('form', $form)); ?>
            <?= $this->formRow($form->get('spezialstraf_v')->setOption('form', $form)); ?>
        </div>
    </fieldset>

    <div class="card mb-2">
        <div class="card-body">
            <?= $this->formRow($form->get('chkErstinfo')->setOption('form', $form)); ?>

            <a class="mt-0 w-100 text-left first-info" title="Erstinformation" href="https://www.geld.de/module/geld/data/erstinformation-jdc.pdf" download="https://www.geld.de/module/geld/data/erstinformation-jdc.pdf" target="_blank">Erstinformation herunterladen</a>

            <div class="accordion mt-3">
                <details class="accordion-item border-bottom-0">
                    <summary class="accordion-button" id="headingTwo">
                        <div class="accordion-header user-select-none">
                            Mitteilung zur Beratungsgrundlage, § 60 VVG
                        </div>
                    </summary>
                    <div class="accordion-body border-bottom">
                        <p>
                            Im durchgeführten Produktvergleich wurden Hausratversicherungsverträge (nachfolgend das Versicherungsprodukt genannt) von 26 Versicherern und 7 Assekuradeuren (zusammen nachfolgend Gesellschaften genannt) berücksichtigt. Generell berücksichtigt der Vermittler keine so genannten Direktversicherer und Gesellschaften, welche dem Vermittler keine Courtage zahlen oder mit diesem nicht zusammenarbeiten.                    </p>
                        <p>
                            Nach der Recherche des Vergleichsprogrammherstellers, die anhand der von der Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin) veröffentlichten Versichererlisten<sup>1</sup> und anderer öffentlich zugänglicher Quellen durchgeführt wurde, bieten das Versicherungsprodukt 91 Versicherer auf dem deutschen Versicherungsmarkt an. Aufgrund des Umstandes, dass die BaFin keine gesonderte Versichererliste für das Versicherungsprodukt veröffentlich hat, und der eingeschränkten Recherchemöglichkeiten sind allerdings bzgl. der genannten Zahl der Versicherer Abweichungen möglich. Ferner sind auf dem deutschen Versicherungsmarkt Assekuradeure tätig, die für die Versicherer hinsichtlich des Versicherungsprodukts spezielle Deckungskonzepte entwickeln und diese unter dem Namen des Assekuradeurs am Markt anbieten. Eine Angabe der Zahl der Assekuradeure ist dem Vermittler nicht möglich, da die BaFin diesbzgl. keine Listen veröffentlicht.                    </p>
                        <p>
                            Die Empfehlung des Vermittlers beruht demnach auf einer eingeschränkten Versicherer- und Vertragsauswahl und damit auf einer eingeschränkten Beratungsgrundlage des Vermittlers.                    </p>
                        <p>
                            Dem Vermittler ist nicht bekannt, welchen Marktanteil die berücksichtigten Gesellschaften und Versicherungsverträge im Verhältnis zum gesamten deutschen Versicherungsmarkt halten. Der Vermittler hat keinen Zugang zu etwaigen Statistiken, aus denen er auch nur schätzungsweise Informationen zum Marktanteil der berücksichtigten Gesellschaften und Versicherungsverträge ableiten könnte. Es ist somit möglich, dass die von dem Vermittler berücksichtigten Gesellschaften und Versicherungsverträge nur einen geringen Marktanteil der in Deutschland angebotenen Versicherungen abdecken.                    </p>
                        <p>
                            Der Produktvergleich beruht nicht auf einer eigenen Marktuntersuchung des Vermittlers, sondern auf den Informationen einer marktüblichen Vergleichssoftware für Versicherungsvermittler.                    </p>
                        <p>
                            Gesellschaften, welche bei dem Produktvergleich berücksichtigt wurden, werden nachfolgend unter "Teilnehmende Gesellschaften" aufgelistet.                    </p>
                        <p>
                            <sup>1</sup> Quelle: https://portal.mvp.bafin.de/database/InstInfo/sucheForm.do
                        </p>
                        <!-- Button trigger modal -->
                        <a class="text-center d-block col-12 info-layer-trigger" data-layer="insurerList">
                            Teilnehmende Gesellschaften
                        </a>
                    </div>
                </details>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body no-margin">
            <div class="row align-items-center">
                <div class="col-sm-8">
                    <div class="row g-0 align-items-center">
                        <div class="col-1 align-middle fs-1"><i class="bi bi-telephone-fill"></i></div>
                        <div class="col-4">
                            <p>Bei Rückfragen stehen wir Ihnen gerne telefonisch zur Verfügung.</p>
                            <p><a href="tel:+49xx" title="Hotline" class="fs-5">xx</a></p>
                            <p><span class="fs-6">Mo - Fr:  xx - xx Uhr</span></p>
                        </div>
                        <button class="btn info-layer-trigger col-1 align-middle fs-1" data-layer="info-layer-consulting"><i class="bi bi-question-circle"></i></button>
                    </div>
                </div>

                <div class="col-sm-4 pt-2">
                    <?= $this->formRow($form->get('btn_berechnen')->setOption('form', $form)); ?>
                </div>
            </div>
        </div>
    </div>

    <?= $this->formHidden($form->get('zahlweise')->setOption('form', $form)); ?>

    <?= $this->form()->closeTag(); ?>
    <div class="text-wrapper">
        <strong>Lorem ipsum dolor sit amet, consetetur</strong>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
    </div>
</div>

<dialog class="modal" id="info-layer-consulting" aria-hidden="true" aria-modal="true" aria-label="an info layer to show something">
    <div class="modal-dialog">
        <div class="modal-content">
            <header class="modal-header">
                <h5 class="modal-title" id="modal-title-consulting"></h5>
                <button type="button" class="btn-close close" aria-label="Close" data-bs-dismiss="modal"></button>
            </header>
            <section class="modal-body">
                <div class="container-fluid">
                    <div class="row g-0">
                        <div class="col-6">
                            <h4>Sie möchten eine Beratung?</h4>
                            <div class="col-1 align-middle fs-1"><i class="bi bi-telephone-fill"></i></div>
                            <div>
                                <span class="consulting-waiver-hotline">
                                    <a href="tel:+49xx" title="Hotline" class=" telephone">xx</a>
                                </span>
                                <span class="consulting-waiver-business-hours">
                                    <span class="description">Mo - Fr:  xx - xx Uhr</span>
                                </span>
                            </div>
                        </div>
                        <div class="col-6">
                            <h4>Schneller zum Vertrag?</h4>
                            <div class="layer-consulting-waiver-description">
                                <p>So kommen Sie direkt zu Ihrer Versicherung</p>
                                <ol class="pl-3">
                                    <li>Klicken Sie auf "Berechnen".</li>
                                    <li>Machen Sie die nötigen Angaben.</li>
                                    <li>Bestätigen Sie vor dem Abschluss, dass Sie keine Beratung benötigen.</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</dialog>

<?php $this->headLink()->appendStylesheet($this->viteUrl()->file('node_modules/bootstrap/dist/css/bootstrap.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->file('public/css/rs.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->file('public/css/help.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->file('public/css/navigation.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->file('public/css/accordion.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->headLink()->appendStylesheet($this->viteUrl()->file('public/css/validation.css'), 'screen', ['rel' => 'stylesheet']); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->file('public/js/form.ts')); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->file('public/js/rs.ts')); ?>
<?php $this->inlineScript()->appendFile($this->viteUrl()->file('public/js/dialog.ts'), 'module'); ?>
