<div class="content content-about-us">
    <div class="row section-1">
        <div class="col-12">
            <div class="box-text">
                <h1 class="headline primary">Über uns.</h1>
                <div class="text">
                    <strong>Lorem ipsum dolor sit amet, consetetur</strong>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore</p>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row section-2 bg-grey">
        <div class="col-12">
            <div class="box-text">
                <div class="text">
                    <p class="font-italic">"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita"</p>
                </div>
            </div>
        </div>
    </div>
</div>
