<?php // Platzhalter für Node JS um die Scripte zu rendern ?>

<?php
$this->inlineScript()->setAutoEscape(false);
$this->inlineScript()->appendFile(
    'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js',
    'text/javascript',
    [
        'integrity' => 'sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0',
        'crossorigin' => 'anonymous',
    ]
);
?>

<?= $this->inlineScript(); ?>
