<?php // Platzhalter für Node JS um die Scripte zu rendern ?>

<?php
$this->inlineScript()->setAutoEscape(false);
//$this->inlineScript()->appendFile(
//    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js',
//    'text/javascript',
//    [
//        'integrity' => 'sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL',
//        'crossorigin' => 'anonymous',
//    ]
//);
?>

<?= $this->inlineScript(); ?>
