<?php
// Wenn neue Dateien hinzukommen, bitte nicht vergessen den Node-Minifier anzupassen. Dort müssen neue Dateien ebenfalls
// hinzugefügt werden. Dieser liegt unter, /build/jsminify.run.js

$this->headLink()->setAutoEscape(false);
$this->headLink()->appendStylesheet(
    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.css',
    'screen',
    [
        'rel'         => 'stylesheet',
        'integrity'   => 'sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN',
        'crossorigin' => 'anonymous',
    ]
);

$this->headLink()->appendStylesheet('/css/styles.css', 'screen', ['rel' => 'stylesheet']);
?>

<?= $this->headLink(); ?>

<?= $this->headStyle(); ?>
