<?php
// Wenn neue Dateien hinzukommen, bitte nicht vergessen den Node-Minifier anzupassen. Dort müssen neue Dateien ebenfalls
// hinzugefügt werden. Dieser liegt unter, /build/jsminify.run.js

$this->headLink(
  [
    'href' => 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css',
    'rel' => 'stylesheet',
    'integrity' => 'sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl',
    'crossorigin' => 'anonymous',
  ]
);
?>

<?= $this->headLink(); ?>

<?= $this->headStyle(); ?>
