<footer class="footer">
    <div class="container">
        <div class="row align-items-md-center">
            <div class="col-3 col-md-2">
                <a class="footer-logo" href="<?= $this->serverUrl('/') ?>" title="zur Startseite"></a>
            </div>
            <div class="col-6 col-md-10 offset-1 offset-md-0">
                <div class="row justify-content-between align-items-md-center">
                    <div class="col-12 col-md-8">
                        <?= $this->navigation('Mimmi20\\Mezzio\\Navigation\\Bottom')->menu()->renderMenu(null, ['ulClass' => 'list-inline text-center text-lg-right mb-0 footer-list', 'liActiveClass' => 'active']); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
