<?php
/** @var $request \Psr\Http\Message\ServerRequestInterface */
?>

<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="<?= $this->serverUrl('/') ?>" title="Hier gelangen Sie zur Startseite">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkupBottom" aria-controls="navbarNavAltMarkupBottom" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavAltMarkupBottom" class="collapse navbar-collapse">

            <?= $this->navigation('Mimmi20\\Mezzio\\Navigation\\Bottom')->menu()->setIndent(28)->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'pills' => true, 'style' => 'ul', 'sublink' => 'details', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'ulClass' => 'justify-content-end']); ?>

        </div>
    </div>
</nav>

<!-- Language:       <?= $this->escapeHtml(isset($request) && $request->getAttribute('language') ?? 'not set') ?> -->
<!-- Locale:         <?= $this->escapeHtml(isset($request) && $request->getAttribute('locale') ?? 'not set') ?> -->
<!-- Default Locale: <?= $this->escapeHtml(Locale::getDefault()) ?> -->
