<section class="id24__s-content-wrapper container content content-imprint">
    <div class="row section-1">
        <div class="col-12">
            <h1 class="headline">Impressum</h1>
            <p>
                <strong>InsureDirect24 Assekuranz GmbH Versicherungsmakler</strong><br/>
                Rotdornweg 46<br/>
                D-91126 Schwabach<br/>
                Telefon: +49 911 9646-6894<br/>
                E-Mail-Adresse: <a href="mailto:info@insuredirect24.de">info@insuredirect24.de</a><br/>
                Internet: <a href="www.insuredirect24.de">www.insuredirect24.de</a>
            </p>
            <p>
                Geschäftsführer: Jürgen Wahner, Gerlinde Wanke<br/>
                Handelsregister-Nummer: HRB 37162<br/>
                Sitz und Registergericht: Nürnberg<br/>
                Register I Erlaubnis<br/>
                IHK für München und Oberbayern<br/>
                Max-Joseph-Straße 2<br/>
                80333 München<br/>
                <a href="www.ihk-muenchen.de">www.ihk-muenchen.de</a><br/>
                Registrierungsnummer: D-9A53-S1229-98
            </p>
            <p>
                Datenschutzbeauftragte: Frau Gerlinde Wanke<br/>
                Compliance und Datenschutz<br/>
                Ostendstrasse 100<br/>
                90334 Nürnberg<br/>
                Telefon: 0911-531-2322<br/>
                E-Mail-Adresse: <a href="mailto:gerlinde.wanke@nuernberger.de">gerlinde.wanke@nuernberger.de</a>
            </p>
            <p>
                Vermögenschaden-Haftpflichtversicherung: Deckungssumme 10 Mio. EURO<br/>
                Mitteilungspflichten der InsureDirect24 Assekuranz GmbH (nachstehend "Makler" genannt):<br/>
                Gemeinsame Stelle<br/>
                Deutscher Industrie-und Handelskammertag (DIHK) e.V.<br/>
                Breite Str. 29<br/>
                10178 Berlin<br/>
                <a href="www.vermittlerregister.info">www.vermittlerregister.info</a><br/>
                Telefon:  0180-600-58-50 (Hotline)<br/>
                <small>(Festnetzpreis 0,20 € / Anruf; Mobilfunkpreise maximal 0,60 € / Anruf)</small>
            </p>
            <p>
                <strong>Beteiligungen</strong><br/>
                Der Makler hat keinerlei Beteiligungen an Stimmrechten oder Kapital > 10 %, weder von noch an einem Versicherungsunternehmen.<br/>
                Die NÜRNBERGER Beteiligungs-Aktiengesellschaft ist indirekt zu 49 Prozent an den Stimmrechten und am Kapital des Maklers beteiligt.<br/>
                Schlichtungsstellen - außergerichtliche Streitbeilegung:<br/>
                Versicherungsombudsmann e.V.<br/>
                Postfach 08 06 32<br/>
                10006 Berlin<br/>
                <a href="www.versicherungsombudsmann.de">www.versicherungsombudsmann.de</a>
            </p>
        </div>
    </div>
</section>
