<?php
/* @var $form \Laminas\Form\Form */

$salutation = $form->get('anrede');
$salutation->setLabelAttributes([
    'class' => 'id24-required'
]);

$firstname = $form->get('vorname');
$firstname->setAttribute('id', $firstname->getAttribute('id'))
    ->setAttribute('class', 'form-control form-control-lg js-filter-name')
    ->setAttribute('autocomplete', 'off')
    ->setAttribute('spellcheck', 'false')
    ->setAttribute('required', true)
    ->setAttribute('data-required-message', 'Bitte geben Sie Ihren Vornamen ein.')
    ->setLabelAttributes([
        'class' => 'id24-required'
    ]);

$surname = $form->get('nachname');
$surname->setAttribute('id', $surname->getAttribute('id'))
    ->setAttribute('class', 'form-control form-control-lg js-filter-name')
    ->setAttribute('autocomplete', 'off')
    ->setAttribute('spellcheck', 'false')
    ->setAttribute('required', true)
    ->setAttribute('data-required-message', 'Bitte geben Sie Ihren Nachnamen ein.')
    ->setLabelAttributes([
        'class' => 'id24-required'
    ]);

$telephone = $form->get('telefon');
$telephone->setAttribute('autocomplete', 'off')
    ->setAttribute('spellcheck', 'false')
    ->setAttribute('class', 'form-control form-control-lg')
    ->setAttribute('id', $telephone->getAttribute('id'))
    ->setAttribute('pattern', '^([+][ ]?[1-9][0-9][ ]?[-]?[ ]?|[(]?[0][ ]?)[0-9]{3,4}[-)/ ]?[ ]?[1-9][-0-9 ]{4,16}$')
    ->setAttribute('data-pattern-message', 'Bitte geben Sie eine gültige Telefonnummer ein.');

$email = $form->get('email');
$email->setAttribute('id', $email->getAttribute('id'))
    ->setAttribute('class', 'form-control form-control-lg js-filter-whitespace js-filter-to-lower')
    ->setAttribute('autocomplete', 'off')
    ->setAttribute('spellcheck', 'false')
    ->setAttribute('required', true)
    ->setAttribute('data-required-message', 'Bitte geben Sie eine E-Mail Adresse ein.')
    ->setAttribute('pattern', '^[a-zA-Z0-9.!#$%&\'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$')
    ->setAttribute('data-pattern-message', 'Bitte geben Sie eine gültige E-Mail Adresse ein.')
    ->setLabelAttributes([
        'class' => 'id24-required'
    ]);

$title = $form->get('title');
$title->setAttribute('id', $title->getAttribute('id'))
    ->setAttribute('class', 'form-control form-control-lg')
    ->setAttribute('autocomplete', 'off')
    ->setAttribute('spellcheck', 'false');

$message = $form->get('message');
$message->setAttribute('id', $message->getAttribute('id'))
    ->setAttribute('class', 'form-control form-control-lg js-autosize')
    ->setAttribute('spellcheck', 'false')
    ->setAttribute('required', true)
    ->setAttribute('data-required-message', 'Bitte geben Sie eine Nachricht ein.')
    ->setLabelAttributes([
        'class' => 'id24-required'
    ]);

$privacyPolicy = $form->get('agb');
$privacyPolicy->setAttribute('class', 'custom-control-input')
    ->setAttribute('id', $privacyPolicy->getAttribute('id'))
    ->setAttribute('required', true)
    ->setAttribute('data-required-message', 'Bitte stimmen Sie den Datenschutzbedingungen zu.')
    ->setLabel($privacyPolicy->getLabel() . '<span class="id24-required-element"></span>')
    ->setLabelAttributes([
        'class' => 'custom-control-label'
    ]);

$sToken = $form->get('sToken');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-colored-default-lg btn-block');

$form->setAttribute('class', 'js-form-validation-base js-ajax-form')->prepare();
?>

<div class="content content-contact">
    <div class="row section-1">
        <div class="col-12">
            <div class="box-text">
                <h1 class="headline primary">Was können wir für Sie tun?</h1>
                <div class="text">
                    <strong>Schreiben Sie uns einfach Ihr Anliegen mit unserem Onlineformular.</strong>
                    <p>Bitte beachten Sie: Die Angabe der Telefonnummer ist keine Pflicht - aber hilfreich. Denn viele Anliegen lassen sich mit einem kurzen Telefonat schneller und unkomplizierter klären als per E-Mail.</p>
                </div>
            </div>
            <div class="box-image">
                <img class="" src="../img/frau.png" alt="Woman">
            </div>
        </div>
    </div>
    <div class="section-2">
        <div class="container">
            <div class="article-right">
                <div class="box-text">
                    <h1 class="headline secondary">InsureDirect24.</h1>
                    <div class="text row justify-content-start align-items-top">
                        <div class="col-12 col-sm-auto col-lg-12">
                            <p>Sie erreichen uns per E-Mail oder Telefon:</p>
                            <p>Montag bis Freitag, 8 bis 18 Uhr</p>
                        </div>
                        <div class="col-12 col-sm-auto col-lg-12">
                            <a href="tel:+4991196466894"><span class="icon id24-icon-phone"></span>+49 911 9646-6894</a>
                            <a href="mailto:info@InsureDirect24.de"><span class="at">@</span>info@InsureDirect24.de</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="article-left">
                <?= $this->form()->openTag($form) ?>
                <div class="row">
                    <div class="col-12 col-md-10">
                        <div class="row form-group is-group">
                            <div class="col-auto">
                                <?= $this->formLabel($salutation); ?>
                            </div>
                            <?php foreach ($salutation->getOption('value_options') as $key => $option) : ?>
                                <div class="col-auto">
                                    <div class="custom-control custom-radio">
                                        <input
                                            type="radio"
                                            class="custom-control-input"
                                            id="salutation-<?= $key ?>"
                                            required
                                            data-required-message="Bitte wählen Sie eine Anrede."
                                            name="<?= $salutation->getName() ?>"
                                            value="<?= $option ?>"
                                            <?php if ($salutation->getValue() === $option) : ?> checked="checked"<?php endif; ?> />
                                        <label for="salutation-<?= $key ?>" class="custom-control-label"><?= $option ?></label>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <div class="form-group">
                            <?= $this->formLabel($firstname) ?>
                            <?= $this->formElement($firstname) ?>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <div class="form-group">
                            <?= $this->formLabel($surname) ?>
                            <?= $this->formElement($surname) ?>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <div class="form-group">
                            <?= $this->formLabel($telephone) ?>
                            <?= $this->formElement($telephone) ?>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <div class="form-group">
                            <?= $this->formLabel($email) ?>
                            <?= $this->formElement($email) ?>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <?= $this->formLabel($title) ?>
                            <?= $this->formElement($title) ?>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <?= $this->formLabel($message) ?>
                            <?= $this->formElement($message) ?>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <div class="custom-control custom-checkbox">
                                <?= $this->formElement($privacyPolicy); ?>
                                <?= $this->formLabel($privacyPolicy); ?>
                            </div>
                        </div>
                        <div class="row justify-content-sm-end">
                            <div class="col-12 col-sm-6">
                                <div class="form-group form-buttom mb-md-0">
                                    <?= $this->formButton($submit); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>

