<?php /** @var \Mezzio\Navigation\LaminasView\View\Helper\Navigation\Menu $menu */ ?>
<?php /** @var array $novumConfig */ ?>

<header class="header">
    <div class="container">
        <div class="header-top row justify-content-between align-items-center">
            <div class="col-auto logo-container">
                <a class="logo" href="<?= $this->serverUrl('/') ?>" title="Hier gelangen Sie zur Startseite">
                    <img src="/img/logo_mobil.svg" alt="Logo mobile" class="d-md-none">
                    <img src="/img/logo.svg" alt="Logo Desktop" class="d-none d-md-inline-block">
                </a>
            </div>
            <div class="col-auto header-navigation-toggle d-md-none">
                <label for="navigation-toggle" class="navigation-toggle-button">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </label>
            </div>
            <input type="checkbox" id="navigation-toggle" class="d-none navigation-toggle"/>
            <nav class="col-auto header-navigation pl-md-0">
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['ulClass' => 'header-navigation-list list-unstyled row d-block d-md-flex', 'liActiveClass' => 'active']); ?>
            </nav>
        </div>
    </div>
</header>
