<?= $this->doctype() ?>

<html lang="de"<?php if ($this->doctype()->isXhtml()): ?> xmlns="http://www.w3.org/1999/xhtml"<?php if ($this->doctype()->isRdfa()): ?> xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml"<?php endif; ?><?php endif; ?>>
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Seiten-Titel')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()->setAutoEscape(false)
            ->appendName('description', 'Die Seitenbeschreibung')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->serverUrl('/_icons/apple-touch-icon.png')?>">
        <link rel="icon" type="image/png" sizes="32x32" href="<?= $this->serverUrl('/_icons/favicon-32x32.png')?>">
        <link rel="icon" type="image/png" sizes="192x192" href="<?= $this->serverUrl('/_icons/android-chrome-192x192.png')?>">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= $this->serverUrl('/_icons/favicon-16x16.png')?>">
        <link rel="manifest" href="<?= $this->serverUrl('/_icons/site.webmanifest')?>">
        <link rel="mask-icon" href="<?= $this->serverUrl('/_icons/safari-pinned-tab.svg')?>" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#00badb">
        <meta name="theme-color" content="#ffffff">

        <!-- Styles -->
        <?= $this->partial('branding::header_styles'); ?>

        <!-- Head Scripts -->
        <?= $this->partial('branding::header_scripts'); ?>
    </head>
    <body class="wrapper" data-bs-theme="light">
        <main class="card mx-3 my-2">
            <?= $this->content ?>
        </main>
        <header class="card m-3 mb-2">
            <div class="card-body">
                <?= $this->partial('header::default'); ?>
            </div>
        </header>
        <footer class="card m-3 mt-2">
            <div class="card-body">
                <?= $this->partial('footer::default'); ?>
            </div>
        </footer>

        <!-- Footer Scripts -->
        <?= $this->partial('branding::footer_scripts'); ?>
    </body>
</html>
