<?php

use Application\Presentation\Form\RegisterForm;
use Application\Presentation\View\Helper\AbsoluteUrl;

?>

<div class="content content-home">
    <div class="section-1 box">
        <div class="container">
            <div class="inner-box">
                <h2 class="headline">Alle Versicherungs&shy;papiere online.</h2>
                <div class="text">
                    Willkommen beim Online-Service Ihrer <strong>InsureDirect24</strong>. Mit unserer WebApp können Sie ganz
                    einfach Ihre Versicherungen hinzufügen, verwalten und optimieren.
                </div>
                <a href="<?= $this->escapeHtml($novumConfig['uri']) ?>insuredirect/de/code"
                   title="Jetzt kostenlos registrieren"
                   class="btn btn-colored-default mb-4"
                   role="button"><span class="d-block d-sm-inline-block">Hier mit dem persönlichen Code</span> aus Ihrer Einladung registrieren</a>
                <div class="link-container"><a href="<?= $this->escapeHtml($novumConfig['uri']) ?>insuredirect/de/register" title="Registrierung ohne Code">Registrierung ohne Code</a> </div>
                <div class="link-container text-right"><a href="<?= $this->escapeHtml($novumConfig['uri']) ?>insuredirect/de/login" title="Anmelden">Anmelden</a> </div>
            </div>
            <div class="box-teaser"></div>
        </div>
    </div>

    <div class="section-2 box-gray">

        <div id="carouselVideo" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselVideo" data-slide-to="0" class="active"></li>
                <li data-target="#carouselVideo" data-slide-to="1"></li>
                <li data-target="#carouselVideo" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-12 col-md-6 box box-content">
                                <h2 class="headline">Die InsureDirect-WebApp schnell und einfach erklärt.</h2>
                                <div class="text">
                                    <strong>INSUREDIRECT24 – ENDLICH.JEDERZEIT.EINFACH</strong>
                                    <p class="mt-3">In den Videos erfahren Sie, wie einfach es sein kann. Gleich bei InsureDirect24 registrieren
                                        und Sie erhalten einen praktischen Gesamtüberblick Ihrer Ver&shy;sicher&shy;ungen. Machen Sie Schluss
                                        mit dem lästigen Papier&shy;kram! Mit unserer WebApp – sämtliche Versicher&shy;ungs&shy;unterlagen immer und
                                        überall griffbereit - ob zuhause am Desktop-PC oder unterwegs mit dem Smartphone.</p>
                                    <strong>SO WIRD AUS VERUNSICHERUNG WIEDER VERSICHERUNG</strong>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 box order-md-first">
                                <div class="box-video">
                                    <div class="video-layer playstate">
                                        <img src="/img/play.svg" alt="play" title="play" class="video-play">
                                        <img src="/img/pause.svg" alt="pause" title="pause" class="video-pause">
                                    </div>
                                    <video class="js-video" preload="none" poster="/img/teil1.png">
                                        <source src="/video/teil1.mp4" type="video/mp4">
                                        <source src="/video/teil.webm" type="video/webm">
                                        <source src="/video/teil.ogv" type="video/ogg">
                                    </video>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-12 col-md-6 box box-content">
                                <h2 class="headline">Die InsureDirect-WebApp schnell und einfach erklärt.</h2>
                                <div class="text">
                                    <strong>INSUREDIRECT24 – ENDLICH.JEDERZEIT.EINFACH</strong>
                                    <p class="mt-3">In den Videos erfahren Sie, wie einfach es sein kann. Gleich bei InsureDirect24 registrieren
                                        und Sie erhalten einen praktischen Gesamtüberblick Ihrer Ver&shy;sicher&shy;ungen. Machen Sie Schluss
                                        mit dem lästigen Papier&shy;kram! Mit unserer WebApp – sämtliche Versicher&shy;ungs&shy;unterlagen immer und
                                        überall griffbereit - ob zuhause am Desktop-PC oder unterwegs mit dem Smartphone.</p>
                                    <strong>SO WIRD AUS VERUNSICHERUNG WIEDER VERSICHERUNG</strong>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 box order-md-first">
                                <div class="box-video">
                                    <div class="video-layer playstate">
                                        <img src="/img/play.svg" alt="play" title="play" class="video-play">
                                        <img src="/img/pause.svg" alt="pause" title="pause" class="video-pause">
                                    </div>
                                    <video class="js-video" preload="none" poster="/img/teil2.png">
                                        <source src="/video/teil2.mp4" type="video/mp4">
                                        <source src="/video/tei2.webm" type="video/webm">
                                        <source src="/video/tei2.ogv" type="video/ogg">
                                    </video>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-12 col-md-6 box box-content">
                                <h2 class="headline">Die InsureDirect-WebApp schnell und einfach erklärt.</h2>
                                <div class="text">
                                    <strong>INSUREDIRECT24 – ENDLICH.JEDERZEIT.EINFACH</strong>
                                    <p class="mt-3">In den Videos erfahren Sie, wie einfach es sein kann. Gleich bei InsureDirect24 registrieren
                                        und Sie erhalten einen praktischen Gesamtüberblick Ihrer Ver&shy;sicher&shy;ungen. Machen Sie Schluss
                                        mit dem lästigen Papier&shy;kram! Mit unserer WebApp – sämtliche Versicher&shy;ungs&shy;unterlagen immer und
                                        überall griffbereit - ob zuhause am Desktop-PC oder unterwegs mit dem Smartphone.</p>
                                    <strong>SO WIRD AUS VERUNSICHERUNG WIEDER VERSICHERUNG</strong>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 box order-md-first">
                                <div class="box-video">
                                    <div class="video-layer playstate">
                                        <img src="/img/play.svg" alt="play" title="play" class="video-play">
                                        <img src="/img/pause.svg" alt="pause" title="pause" class="video-pause">
                                    </div>
                                    <video class="js-video" preload="none" poster="/img/teil3.png">
                                        <source src="/video/teil3.mp4" type="video/mp4">
                                        <source src="/video/tei3.webm" type="video/webm">
                                        <source src="/video/tei3.ogv" type="video/ogg">
                                    </video>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselVideo" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon icon id24-icon-arrow-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselVideo" role="button" data-slide="next">
                <span class="carousel-control-next-icon icon id24-icon-arrow-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="section-3">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-5 col-xl-4 box">
                    <h2 class="headline">Volle Kontrolle &uuml;ber alle Versicherungen und Dokumente</h2>
                    <ul class="list-unstyled list">
                        <li>Pers&ouml;nliche Beratung auf Wunsch nur einen Klick entfernt.</li>
                        <li>Per Smartphone, Tablet oder Desktop aufrufbar.</li>
                        <li>Bedarfsanalyse und Vergleichsrechner zur Optimierung.</li>
                    </ul>
                </div>
                <div class="d-none d-md-block col-7 position-relative box-image-wrapper">
                    <div class="box-image"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="section-4 box-gray">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 box box-text-wrapper">
                    <div class="inner-box row justify-content-end">
                        <div class="col-auto col-inner-box">
                            <h2 class="headline">Optimieren Sie Ihre Verträge schnell und einfach.</h2>
                            <div class="text">
                                Sie wünschen zusätzliche oder bessere Leistungen oder sind einfach nicht mehr zufrieden mit
                                dem aktuellen Vertrag? Mit InsureDirect24 können Sie über 2.000 Tarife in 25 Sparten vergleichen
                                und damit jährlich bis zu 60 Prozent sparen.

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 box-image-wrapper">
                    <div class="box-image"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="section-5 box-gray">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 box box-text-wrapper">
                    <h2 class="headline">Sch&auml;den online melden</h2>
                    <div class="text">
                        <strong>Besonders hilfreich ist die InsureDirect24-WebApp im Schadenfall.</strong>
                        <p>Über unser Schadensformular werden dem Versicherer alle notwendigen Angaben zum Schaden schnell
                            und einfach übermittelt.</p>
                        Außerdem können Sie Bilder und benötigte Dokumente ganz bequem hochladen.
                    </div>
                </div>
                <div class="col-12 col-md-6 box-image-wrapper order-md-first">
                    <div class="box-image"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="section-6">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 align-self-md-center box">
                    <div class="inner-box row justify-content-end">
                        <div class="col-auto col-inner-box">
                            <h2 class="headline">Expertenberatung zu allen Versicherungs&shy;fragen per Telefon oder E-Mail</h2>
                            <div class="text">
                                <div class="text">
                                    Sie erreichen unser Team per E-Mail oder telefonisch von Montag bis Freitag in der Zeit von 8:00 bis
                                    18:00 Uhr.
                                </div>
                                <div class="box-tel">
                                    <span class="icon id24-icon-phone"></span>
                                    <a class="id24-phone" href="tel:+4991196466894" title="Mo-Fr 8:00 bis 18:00 Uhr" data-event-label="home" data-event-action="<?= $this->serverUrl('/') ?>" data-event-category="call">
                                        <span class="id24-phone-number">+49 911 9646-6894</span>
                                    </a>
                                </div>
                                <div class="box-mail">
                                    <strong>@</strong> info@insuredirect24.de
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 box box-image-wrapper">
                    <div class="box-image"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="section-7 box box-gray">
        <div class="container">
            <div class="inner-box-right">
                <h2 class="headline">Mit wenigen Klicks registrieren und alle Vorteile nutzen!</h2>
            </div>
            <div class="inner-box-left">
                <div class="api-container position-relative" data-container="<?= $this->escapeHtml($novumConfig['oid']['id24']); ?>"></div>
                <?= $this->showNovumRegistrationForm($novumPartner, true); ?>
            </div>
        </div>
    </div>
</div>
