name: "Lint GitHub Actions workflows"

on:
  pull_request:
    paths:
      - ".github/**"

jobs:
  actionlint:

    uses: "mimmi20/ci/.github/workflows/lint-actions.yml@8.3"
    with:
      skip-nasm-install: false
      skip-libimagequant-install: false
      skip-librabbitmq-install: false
      skip-libgif-install: false
