<?php /** @var \Mezzio\Navigation\LaminasView\View\Helper\Navigation\Menu $menu */ ?>
<?php /** @var array $novumConfig */ ?>

<header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= $this->serverUrl('/') ?>" title="Hier gelangen Sie zur Startseite">
                <img src="/img/logo_mobil.svg" alt="Logo mobile" class="d-md-none">
                <img src="/img/logo.svg" alt="Logo Desktop" class="d-none d-md-inline-block">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>A</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 0]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>A2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 1]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-success">
                <pre>B2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 1, 'maxDepth' => 1]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>A3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 2]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-success">
                <pre>B3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 1, 'maxDepth' => 2]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-warning">
                <pre>C3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 2, 'maxDepth' => 2]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>D</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => true, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 0]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>D2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => true, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 1]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>D3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => true, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 2]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-info">
                <pre>G</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => true, 'renderParents' => false, 'minDepth' => 0, 'maxDepth' => 0]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-info">
                <pre>G2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => true, 'renderParents' => false, 'minDepth' => 0, 'maxDepth' => 1]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-secondary">
                <pre>J</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderSubMenu(null); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>K</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => false, 'minDepth' => 0, 'maxDepth' => 0]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>K2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => false, 'minDepth' => 0, 'maxDepth' => 1]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-success">
                <pre>L2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => false, 'minDepth' => 1, 'maxDepth' => 1]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>K3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => false, 'minDepth' => 0, 'maxDepth' => 2]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-success">
                <pre>L3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => false, 'minDepth' => 1, 'maxDepth' => 2]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-warning">
                <pre>M3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => false, 'minDepth' => 2, 'maxDepth' => 2]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-warning">
                <pre>N</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenuLevel(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 0], 0); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>N2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 1]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-success">
                <pre>O2</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 1, 'maxDepth' => 1]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-danger">
                <pre>N3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 2]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-success">
                <pre>O3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 1, 'maxDepth' => 2]); ?>
            </div>
            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-warning">
                <pre>P3</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 2, 'maxDepth' => 2]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-warning">
                <pre>Q</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'sublink' => 'button', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 2]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-warning">
                <pre>R</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'sublink' => 'span', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 2]); ?>
            </div>

            <div id="navbarNavAltMarkup" class="collapse navbar-collapse bg-warning">
                <pre>S</pre>
                <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['in-navbar' => true, 'fill' => true, 'style' => 'ul', 'sublink' => 'details', 'onlyActiveBranch' => false, 'renderParents' => true, 'minDepth' => 0, 'maxDepth' => 2]); ?>
            </div>
        </div>
    </nav>
</header>
