<?php /** @var \Mezzio\Navigation\LaminasView\View\Helper\Navigation\Menu $menu */ ?>
<?php /** @var array $novumConfig */ ?>

<header class="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= $this->serverUrl('/') ?>" title="Hier gelangen Sie zur Startseite">
                <img src="/img/logo_mobil.svg" alt="Logo mobile" class="d-md-none">
                <img src="/img/logo.svg" alt="Logo Desktop" class="d-none d-md-inline-block">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <?= $this->navigation('Mezzio\\Navigation\\Top')->menu()->renderMenu(null, ['ulClass' => 'navbar-nav', 'liActiveClass' => 'active']); ?>
                </div>
            </div>
        </div>
    </nav>
</header>
